RegisterNetEvent('esx:useItem')
AddEventHandler('esx:useItem', function(itemName)
TriggerClientEvent("esx_animations:playEmote", source, "drink")
TriggerClientEvent("esx_animations:stopEmote", nil")
	TriggerClientEvent("esx:showNotification", source, "Je nam een pijnstiller, en voelt je langzamerhand steeds beter.")
        local xPlayer = ESX.GetPlayerFromId(source)
       		local playerPed = xPlayer.playerPed
		xPlayer.removeInventoryItem('painkiller', 1)	
				Wait(100) 
				TriggeEvent ('esx_status:add','health', 10)
				Wait(100) 
				TriggeEvent ('esx_status:add','health', 15)
				Wait(100) 
				TriggeEvent ('esx_status:add','health', 20)
				Wait(100) 
				TriggeEvent ('esx_status:add','health', 30)
		TriggerClientEvent("esx:showNotification", source, "Je bent compleet herstelt!")
		TriggerEvent('esx_status:add', 'health', 100)
	end)
end
